services:
  db:
    build:
      context: .
      dockerfile: backend/postgres-init/Dockerfile
    env_file: ./backend/.env
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # init script is baked into custom image to avoid Windows mount/exec-bit issues

  app-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/src:/app/src
      - ./backend/tests:/app/tests
    environment:
      - RUN_MIGRATIONS=1

  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend/app/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/.env:/app/.env
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    entrypoint:
      - bash
      - /app/wait-for-it.sh
      - db:5432
      - --timeout=30
      - --
      - pytest

  app-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  db_data:
