services:
  db:
    image: postgres:16.2-alpine
    env_file: ./backend/.env
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.db.sh:/docker-entrypoint-initdb.d/init.db.sh

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/src:/app/src
      - ./backend/tests:/app/tests

  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: ["pytest"]

volumes:
  db_data:
