services:
  db:
    image: postgres:latest
    env_file: .env.production
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.db.sh:/docker-entrypoint-initdb.d/init.db.sh

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: ["pytest"]

volumes:
  db_data:
