services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  db_data:
