"""Make task title not nullable

Revision ID: 246e85e751f7
Revises: 800d86faa2c6
Create Date: 2025-08-06 14:26:09.543547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "246e85e751f7"
down_revision: Union[str, Sequence[str], None] = "800d86faa2c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE tasks SET title = 'Untitled' WHERE title IS NULL;")
    # Ensure that existing tasks have a default title
    op.alter_column("tasks", "title", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "title", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###
